[코랩(Colab)으로 열기](https://colab.research.google.com/github/dhnam-data/Datafile/blob/main/StatisticsHealthCare/code/13_2_%EB%8F%85%EB%A6%BD%ED%91%9C%EB%B3%B8_T_%EA%B2%80%EC%A0%95.ipynb)

귀무가설(H0): 일반가구와 저소득층 가구의 평균 민간의료보험료는 같다. [H0: μ1 ＝ μ2]

대립가설(H1): 일반가구와 저소득층 가구의 평균 민간의료보험료는 같지 않다. [H1: μ1 ≠ μ2]

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None) # 컬럼 전체보기


# 파일 불러오기
df = pd.read_excel("https://github.com/dhnam-data/Datafile/raw/refs/heads/main/StatisticsHealthCare/data/1.%ED%8F%89%EA%B7%A0%EB%B9%84%EA%B5%90.xlsx")

print(df.shape)
df.head()

(7300, 6)

   h20_g3  h2005_3aq2  h20_hc_n_all  h2007_3aq8  h2007_6aq13  h20_g2
0       2         0.0             2        58.0         18.7      10
1       1        23.0             1        20.0          7.0      10
2       1         0.0             1        15.0          0.0      10
3       1        23.0             1        34.0         13.8      10
4       2         0.0             2        10.0          0.0      10

In [2]:
df = df.dropna(subset=['h2005_3aq2'])
cond1 = df['h20_hc_n_all'] == 1 # 일반가구
cond2 = df['h20_hc_n_all'] == 2 # 저소득층 가구
gen_df = df[cond1]
low_df = df[cond2]

In [3]:
from scipy import stats

levene_result = stats.levene(
    gen_df['h2005_3aq2'],
    low_df['h2005_3aq2'],
    center='mean'
)

print('Levene 통계량:', levene_result.statistic)
print('p값:', levene_result.pvalue)

Levene 통계량: 1297.8950855631829
p값: 9.619448371261953e-262

In [4]:
from scipy import stats

# 등분산
display(stats.ttest_ind(gen_df['h2005_3aq2'], low_df['h2005_3aq2'], equal_var=True))

# 등분산을 가정하지 않음
display(stats.ttest_ind(gen_df['h2005_3aq2'], low_df['h2005_3aq2'], equal_var=False))

TtestResult(statistic=np.float64(45.20940924425194), pvalue=np.float64(0.0), df=np.float64(7298.0))

TtestResult(statistic=np.float64(53.222092249155864), pvalue=np.float64(0.0), df=np.float64(6484.772518058413))

In [5]:
!pip install pingouin -q
import pingouin as pg
import pandas as pd

In [6]:
df = df.dropna(subset=['h2005_3aq2'])
cond1 = df['h20_hc_n_all'] == 1 # 일반가구
cond2 = df['h20_hc_n_all'] == 2 # 저소득층 가구
gen_df = df[cond1]
low_df = df[cond2]

# levene의 등분산 검정
levene_test = pg.homoscedasticity([gen_df['h2005_3aq2'].to_numpy(), low_df['h2005_3aq2'].to_numpy()], method='levene', center='mean')

display(levene_test)

result_ind = pg.ttest(gen_df['h2005_3aq2'], low_df['h2005_3aq2'], correction='auto') # 기본값
# result_ind = pg.ttest(gen_df['h2005_3aq2'], low_df['h2005_3aq2'], correction=False) # 등분산
# result_ind = pg.ttest(gen_df['h2005_3aq2'], low_df['h2005_3aq2'], correction=True) # 등분산을 가정하지 않음

display(result_ind)

                  W           pval  equal_var
levene  1297.895086  9.619448e-262      False

,T,dof,alternative,p_val,CI95,cohen_d,power,BF10
T_test,53.222092,6484.772518,two-sided,0.0,"[25.99, 27.98]",1.086957,1.0,inf