[코랩(Colab)으로 열기](https://colab.research.google.com/github/dhnam-data/Datafile/blob/main/StatisticsHealthCare/code/13_3_%EB%8C%80%EC%9D%91%ED%91%9C%EB%B3%B8_T_%EA%B2%80%EC%A0%95.ipynb)

귀무가설(H0): 심화교육 전 시험 점수와 심화교육 후 시험 점수의 평균값은 같다.
- (심화교육 전후 통계학 시험 점수의 차이에 대한 모집단 평균은 0이다. [H0: μd ＝ 0])


대립가설(H1): 심화교육 전 시험 점수와 심화교육 후 시험 점수의 평균값은 같지 않다.
- (심화교육 전후 통계학 시험 점수의 차이에 대한 모집단 평균은 0이 아니다.[H1: μd ≠ 0])

※ **μd = μ1 - μ2**

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None) # 컬럼 전체보기

df = pd.read_excel("https://github.com/dhnam-data/Datafile/raw/refs/heads/main/StatisticsHealthCare/data/13-1.%ED%8F%89%EA%B7%A0%EB%B9%84%EA%B5%90.xlsx")

print(df.shape)
df.head()

(200, 3)

   id  pre  post
0   1   83    82
1   2   49    58
2   3   41    63
3   4   72    77
4   5   58    68

In [2]:
# pre: 교육전
# post: 교육후

# 결측치 제거
df = df.dropna(subset=['pre', 'post'])

from scipy import stats

display(stats.ttest_rel(df['pre'], df['post']))

TtestResult(statistic=np.float64(-16.01247443671383), pvalue=np.float64(1.2614854939428556e-37), df=np.int64(199))

In [3]:
!pip install pingouin -q
import pandas as pd
import pingouin as pg

result = pg.ttest(df['pre'], df['post'], paired=True)
display(result)

,T,dof,alternative,p_val,CI95,cohen_d,power,BF10
T_test,-16.012474,199,two-sided,1.261485e-37,"[-9.37, -7.31]",0.545243,1.0,2.027e+34