[코랩(Colab)으로 열기](https://colab.research.google.com/github/dhnam-data/Datafile/blob/main/StatisticsHealthCare/code/14_1_%EC%9D%B4%EB%B3%80%EB%9F%89_%EC%83%81%EA%B4%80%EA%B4%80%EA%B3%84.ipynb)

귀무가설(H0): 경상소득과 민간의료보험료의 모집단 상관계수는 0이다.

대립가설(H1): 경상소득과 민간의료보험료의 모집단 상관계수는 0이 아니다.

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None) # 컬럼 전체보기

# 파일 불러오기
df = pd.read_excel("https://github.com/dhnam-data/Datafile/raw/refs/heads/main/StatisticsHealthCare/data/3.%EC%83%81%EA%B4%80%EB%B6%84%EC%84%9D.xlsx")
print(df.shape)
df.head()

(7300, 3)

   h20_cin  h2005_3aq2  h2001_1
0    713.0         0.0        1
1   3206.0        23.0        1
2   2216.0         0.0        1
3   6729.0        23.0        4
4   1968.0         0.0        1

In [2]:
from scipy import stats

# h20_cin: 경상소득
# h2005_3aq2: 민간의료보험 월납부액
# df = df[['h20_cin', 'h2005_3aq2']].dropna()


correlation = stats.pearsonr(df['h20_cin'], df['h2005_3aq2'])

print(correlation)

display(df.corr(method='pearson'))

PearsonRResult(statistic=np.float64(0.5658936775547323), pvalue=np.float64(0.0))

             h20_cin  h2005_3aq2   h2001_1
h20_cin     1.000000    0.565894  0.623467
h2005_3aq2  0.565894    1.000000  0.562106
h2001_1     0.623467    0.562106  1.000000

In [3]:
!pip install pingouin -q
import pingouin as pg

correlation = pg.pairwise_corr(
    data = df,
    columns = ['h20_cin', 'h2005_3aq2'],
    method='pearson'
)

display(correlation)

display(pg.rcorr(df, method='pearson'))

,X,Y,method,alternative,n,r,CI95,p_unc,BF10,power
0,h20_cin,h2005_3aq2,pearson,two-sided,7300,0.565894,"[0.55, 0.58]",0.0,inf,1.0

           h20_cin h2005_3aq2 h2001_1
h20_cin          -        ***     ***
h2005_3aq2   0.566          -     ***
h2001_1      0.623      0.562       -