[코랩(Colab)으로 열기](https://colab.research.google.com/github/dhnam-data/Datafile/blob/main/StatisticsHealthCare/code/14_2_%ED%8E%B8%EC%83%81%EA%B4%80%EA%B4%80%EA%B3%84.ipynb)

귀무가설(H0): 가구원 수를 보정한 상태에서 경상소득과 민간의료보험료 납부액은 관련성이 없다.

대립가설(H1): 가구원 수를 보정한 상태에서 경상소득과 민간의료보험료 납부액은 관련성이 있다.

In [ ]:
import pandas as pd
pd.set_option('display.max_columns', None) # 컬럼 전체보기

# 파일 불러오기
df = pd.read_excel("https://github.com/dhnam-data/Datafile/raw/refs/heads/main/StatisticsHealthCare/data/14.%EC%83%81%EA%B4%80%EB%B6%84%EC%84%9D.xlsx")
print(df.shape)
df.head()

(7300, 3)

   h20_cin  h2005_3aq2  h2001_1
0    713.0         0.0        1
1   3206.0        23.0        1
2   2216.0         0.0        1
3   6729.0        23.0        4
4   1968.0         0.0        1

In [ ]:
!pip install pingouin -q
import pingouin as pg

# h20_cin: 경상소득
# h2005_3aq2: 민간의료보험 월납부액
# h2001_1: 가구원수
df = df[['h20_cin', 'h2005_3aq2', 'h2001_1']].dropna()


correlation = pg.partial_corr(
    data=df,
    x='h20_cin',
    y='h2005_3aq2',
    covar='h2001_1',
    method='pearson'
)

display(correlation)

display(pg.pcorr(df))

            n         r          CI95          p_val
pearson  7300  0.333167  [0.31, 0.35]  1.035367e-188

             h20_cin  h2005_3aq2   h2001_1
h20_cin     1.000000    0.333167  0.447832
h2005_3aq2  0.333167    1.000000  0.324672
h2001_1     0.447832    0.324672  1.000000