[코랩(Colab)으로 열기](https://colab.research.google.com/github/dhnam-data/Datafile/blob/main/StatisticsHealthCare/code/15_2_%EB%8B%A4%EC%A4%91%EC%84%A0%ED%98%95%ED%9A%8C%EA%B7%80%EB%B6%84%EC%84%9D.ipynb)

귀무가설(H0): 조사대상자의 경상소득, 가구원수는 민간의료보험 납입액에 영향을 미치지 않는다.

대립가설(H1): 조사대상자의 경상소득, 가구원수는 민간의료보험 납입액에 영향을 미친다.

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None) # 컬럼 전체보기

# 파일 불러오기
df = pd.read_excel("https://github.com/dhnam-data/Datafile/raw/refs/heads/main/StatisticsHealthCare/data/4.%ED%9A%8C%EA%B7%80%EB%B6%84%EC%84%9D.xlsx")
print(df.shape)
df.head()

(7300, 3)

   h20_cin  h2005_3aq2  h2001_1
0    713.0         0.0        1
1   3206.0        23.0        1
2   2216.0         0.0        1
3   6729.0        23.0        4
4   1968.0         0.0        1

In [2]:
# h20_cin: 경상소득
# h2005_3aq2: 민간의료보험 월납부액
# h2001_1: 가구원수

df = df[['h20_cin', 'h2005_3aq2', 'h2001_1']].dropna()

from statsmodels.formula.api import ols

result = ols('h2005_3aq2 ~ h20_cin + h2001_1', df).fit()

print(result.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             h2005_3aq2   R-squared:                       0.392
Model:                            OLS   Adj. R-squared:                  0.392
Method:                 Least Squares   F-statistic:                     2351.
Date:                Tue, 20 Oct 2026   Prob (F-statistic):               0.00
Time:                        14:57:08   Log-Likelihood:                -32889.
No. Observations:                7300   AIC:                         6.578e+04
Df Residuals:                    7297   BIC:                         6.580e+04
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -5.7632      0.529    -10.898      0.000      -6.800      -4.727
h20_cin        0.0020   6.77e-05     30.184      0.000       0.002       0.002
h2001_1        8.4864      0.289     29.323      0.000       7.919       9.054
==============================================================================
Omnibus:                     3276.310   Durbin-Watson:                   1.925
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            37583.620
Skew:                           1.843   Prob(JB):                         0.00
Kurtosis:                      13.487   Cond. No.                     1.59e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.59e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

In [3]:
!pip install pingouin -q
import pingouin as pg

pg.linear_regression(X=df[['h20_cin', 'h2001_1']], y=df['h2005_3aq2'])

,names,coef,se,T,pval,r2,adj_r2,CI2.5,CI97.5
0,Intercept,-5.763174,0.528829,-10.897988,1.915966e-27,0.391891,0.391724,-6.799833,-4.726516
1,h20_cin,0.002043,0.000068,30.184433,1.035367e-188,0.391891,0.391724,0.001910,0.002175
2,h2001_1,8.486402,0.289413,29.322820,9.018193e-179,0.391891,0.391724,7.919069,9.053735