[코랩(Colab)으로 열기](https://colab.research.google.com/github/dhnam-data/Datafile/blob/main/StatisticsHealthCare/code/16_%EC%B9%B4%EC%9D%B4%EC%A0%9C%EA%B3%B1%EA%B2%80%EC%A0%95.ipynb)

귀무가설(H0): 성별과 1년간 입원여부는 서로 독립적이다.

대립가설(H1): 성별과 1년간 입원여부는 서로 독립적이지 않다.

In [ ]:
import pandas as pd
pd.set_option('display.max_columns', None) # 컬럼 전체보기

# 파일 불러오기
df = pd.read_excel("https://github.com/dhnam-data/Datafile/raw/refs/heads/main/StatisticsHealthCare/data/16.%EC%B9%B4%EC%9D%B4%EC%A0%9C%EA%B3%B1%EA%B2%80%EC%A0%95.xlsx")
print(df.shape)
df.head()

(14915, 3)

   adm  h20_g3  dis
0    0       2    0
1    0       1    0
2    0       1    0
3    0       1    0
4    0       2    0

In [ ]:
# h20_g3: 성별
# adm: 1년간 입원여부
df = df[['h20_g3', 'adm']].dropna()

# 교차표 생성
table = pd.crosstab(df['h20_g3'], df['adm'])


from scipy import stats

result = stats.chi2_contingency(table, correction=False)

print(result[0],'\n') # 카이제곱 통계량
print(result[1],'\n') # p값
print(result[2],'\n') # 자유도
print(result[3],'\n') # 기대빈도
print(table) # 관측빈도

49.72276371226411

1.7707940483489028e-12

1

[[5939.55051961  754.44948039]
 [7294.44948039  926.55051961]]

adm        0     1
h20_g3
1       6075   619
2       7159  1062

In [ ]:
!pip install pingouin -q
import pingouin as pg


result = pg.chi2_independence(df, 'h20_g3', 'adm', correction=False)

display(result[0]) # 기대빈도
print("\n")

display(result[1]) # 관측빈도
print("\n")

display(result[2]) # 검정결과

adm              0          1
h20_g3
1       5939.55052  754.44948
2       7294.44948  926.55052

adm        0     1
h20_g3
1       6075   619
2       7159  1062

                 test    lambda       chi2  dof          pval    cramer  power
0             pearson  1.000000  49.722764  1.0  1.770794e-12  0.057739    1.0
1        cressie-read  0.666667  49.930108  1.0  1.593211e-12  0.057859    1.0
2      log-likelihood  0.000000  50.417206  1.0  1.242996e-12  0.058140    1.0
3       freeman-tukey -0.500000  50.847880  1.0  9.980901e-13  0.058388    1.0
4  mod-log-likelihood -1.000000  51.336673  1.0  7.780845e-13  0.058668    1.0
5              neyman -2.000000  52.497252  1.0  4.308507e-13  0.059328    1.0